####################################################
# Image: img.reg.3g:15000/kafka:2.10-0.8.2.0
####################################################

FROM img.reg.3g:15000/jdk:1.7.0_67

# Add User
RUN mkdir -p /home/kafka

ADD kafka_2.10-0.8.2.0/ /home/kafka/

EXPOSE 9092
