################################################################
# Image: img.reg.3g:15000/go-ceph:latest
################################################################

FROM img.reg.3g:15000/go-librados:1.8

RUN go get github.com/ceph/go-ceph

ADD Dockerfile /
