#!/bin/bash
i=0
while(($i < 100))
do
	let i++
	echo "{\"log\":\"2015-11-11 10:17:24 +0000 [info]: shutting down fluentd\",\"stream\":\"stdout\",\"time\":\"2015-11-11T10:17:24.895173087Z Hello world~~~~~~~~~~\"}" >> /fuck/aaa
	sleep 0.1
done
