apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  labels:
    name: kibana
spec:
  replicas: 2
  selector:
    name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
      - name: kibana
        image: img.reg.3g:15000/kibana:4.3.1
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources:
          limits:
            cpu: "6"
            memory: "12800Mi"
