apiVersion: v1
kind: ReplicationController
metadata:
  name: push-portal-1
  labels:
    name: push-portal
    role: portal
spec:
  replicas: 1
  selector:
    name: push-portal-1
  template:
    metadata:
      labels:
        name: push-portal-1
    spec:
      containers:
      - name: push-portal
        image: registry.docker:5000/push-portal:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "4"
            memory: "8092Mi"
        livenessProbe:
          httpGet:
            path: /push-portal/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
        volumeMounts:
        - mountPath: /apps/log
          name: storage
      volumes:
      - name: storage 
        rbd: 
          monitors:
            - "10.149.149.1:6789"
          pool: rbd
          image: push-portal-1
          secretRef:
            name: ceph-secret
          fsType: ext4
          readOnly: false
