apiVersion: v1
kind: Service
metadata:
  name: tensorflow
  labels:
    name: tensorflow
spec:
  ports:
  - port: 8880
    name: port1
    targetPort: 8880
    nodePort: 30053
  - port: 8881
    name: port2
    targetPort: 8881
    nodePort: 30054
  - port: 8882
    name: port3
    targetPort: 8882
    nodePort: 30055
  - port: 8884
    name: port4
    targetPort: 8884
    nodePort: 30056
  - port: 8889
    name: port5
    targetPort: 8889
    nodePort: 30057
  type: "NodePort"
  selector:
    name: tensorflow
