################################################################
# Image: img.reg.3g:15000/librados:latest
################################################################

FROM img.reg.3g:15000/ubuntu-base:v3 

RUN apt-get update && apt-get install librados-dev librbd-dev -y
